### ISSUE TITLE
如何对应标注文件和电视剧内容？

### ISSUE THREAD

**Issue by haishiwo** [AIM3-RUC/RUCM3ED#4]
首先感谢您的开源！对于开源的标注文件annotation.json有一些疑问：
1.电视剧版本如何确定？我注意到大部分Dialog的第一个StartTime都是00:00:00:00，是否意味着电视剧片段都不包含片头和片尾？；
2.电视剧集数如何确定？比较了一些标注内容和电视剧后，发现XX_1并不对应XX的第一集，如fendou_1包含的内容没有在《奋斗》的第一集中出现；
3.每个Dialog是否与电视剧的开头对齐？如果不是，能否给出起始时间？

**Comment by JinmingZhao** [comment]
不好意思，最近工作的事情比较忙。目前是时间是我们切割好的对应的Dialogue的时间，我们最近在整理每个Dialogue对应到电视剧的具体时间，预计7月底能Release出来。

感谢关注！

**Comment by haishiwo** [comment]
> 不好意思，最近工作的事情比较忙。目前是时间是我们切割好的对应的Dialogue的时间，我们最近在整理每个Dialogue对应到电视剧的具体时间，预计7月底能Release出来。
> 
> 感谢关注！

好的，多谢！

**Comment by JinmingZhao** [comment]
添加了对应关系的Json文件，有DialogueID 和 电视剧集内的具体时间
