### ISSUE TITLE
请教M3ED数据集下载链接

### ISSUE THREAD

**Issue by jiaqiangwjq** [AIM3-RUC/RUCM3ED#5]
作者您好，恭喜中稿！

        M3ED 作为首个多模态中文情感对话数据集，其意义和优势不言而喻。

        对于这篇工作的内容和方法，我也很感兴趣，很想把文献中的数据跑一下，所以想来咨询一下作者：是否可以共享数据集，以供大家学习和交流。万分感谢！

祝科研顺利，paper 不断！

**Comment by FAFUxrhuang** [comment]
> 作者您好，恭喜中稿！
> 
> ```
>     M3ED 作为首个多模态中文情感对话数据集，其意义和优势不言而喻。
> 
>     对于这篇工作的内容和方法，我也很感兴趣，很想把文献中的数据跑一下，所以想来咨询一下作者：是否可以共享数据集，以供大家学习和交流。万分感谢！
> ```
> 
> 祝科研顺利，paper 不断！

您好，请问您获取到该文的数据集了吗？方便共享一下吗？

**Comment by Shawnie-qi** [comment]
> 作者您好，恭喜中稿！
> 
> ```
>     M3ED 作为首个多模态中文情感对话数据集，其意义和优势不言而喻。
> 
>     对于这篇工作的内容和方法，我也很感兴趣，很想把文献中的数据跑一下，所以想来咨询一下作者：是否可以共享数据集，以供大家学习和交流。万分感谢！
> ```
> 
> 祝科研顺利，paper 不断！

请问您是否获取到原数据集包括视频和音频，能否共享？祝您科研顺利~
